### ISSUE TITLE
Ordering PCB on JLCPCB

### ISSUE THREAD

**Issue by MultiWu** [neg2led/cfxsx#3]
Hi!
How can i order PCB on JLCPCB with assembly?
@neg2led

**Comment by MultiWu** [comment]
I don't know where i can get BOM and CPL files, i tried to make it on KiCad and converting it to JLCPCB format but it didn't work.

**Comment by neggles** [comment]
Hey! Sorry it took me so long to get back to you, I missed this one...

There are pre-built gerbers available here: https://neg2led.github.io/cfxsx/ (scroll down to the bottom)

That said, JLCPCB will not do assembly on these - they don't stock the right M.2 connector, unfortunately.
